# Databricks notebook source
import requests
from typing import Dict, Any, List, Optional

def fetch_from_facebook(url: str, params: Dict[str, Any]) -> Dict[str, Any]:
    """
        Hace una solicitud a la API de Facebook y devuelve la respuesta en formato JSON.
            
                Args:
                        url (str): La URL de la API de Facebook.
                                params (Dict[str, Any]): Parámetros para la solicitud.                                 Returns:
                                            Dict[str, Any]: La respuesta de la API en formato JSON.
                                                """
                                                    print(f"Fetching URL: {url} with params: {params}")
                                                        try:
                                                                response = requests.get(url, params=params)
                                                                        response.raise_for_status()
                                                                                data = response.json()
                                                                                        print(f"Data fetched successfully: {data}")
                                                                                                return data
                                                                                                    except requests.exceptions.RequestException as e:
                                                                                                            print(f"Request failed: {e}")
                                                                                                                    return {}
                                                                                                                        except ValueError as e:
                                                                                                                                print(f"Failed to parse response: {e}")
                                                                                                                                        return {}

                                                                                                                                        def fetch_all_posts(access_token: str, group_id: str) -> List[Dict[str, Any]]:
                                                                                                                                            """
                                                                                                                                                Obtiene todos los posts de un grupo de Facebook utilizando paginación.
                                                                                                                                                    
                                                                                                                                                        Args:
                                                                                                                                                                access_token (str): Token de acceso para la API de Facebook.
                                                                                                                                                                        group_id (str): ID del grupo de Facebook.

                                                                                                                                                                            Returns:
                                                                                                                                                                                    List[Dict[str, Any]]: Lista de posts obtenidos del grupo.
                                                                                                                                                                                        """
                                                                                                                                                                                            url = f"https://graph.facebook.com/{group_id}/feed"
                                                                                                                                                                                                params = {
                                                                                                                                                                                                        'access_token': access_token,
                                                                                                                                                                                                                'limit': 100
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                        all_posts = []
                                                                                                                                                                                                                            
                                                                                                                                                                                                                                while url:
                                                                                                                                                                                                                                        data = fetch_from_facebook(url, params)
                                                                                                                                                                                                                                                posts = data.get('data', [])
                                                                                                                                                                                                                                                        print(f"Fetched {len(posts)} posts")
                                                                                                                                                                                                                                                                all_posts.extend(posts)
                                                                                                                                                                                                                                                                        url = data.get('paging', {}).get('next')
                                                                                                                                                                                                                                                                                if url:
                                                                                                                                                                                                                                                                                            print(f"Next page URL: {url}")

                                                                                                                                                                                                                                                                                                return all_posts

                                                                                                                                                                                                                                                                                                def fetch_comments_for_post(access_token: str, post_id: str) -> List[Dict[str, Any]]:
                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                        Obtiene todos los comentarios de un post específico utilizando paginación.
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                Args:
                                                                                                                                                                                                                                                                                                                        access_token (str): Token de acceso para la API de Facebook.
                                                                                                                                                                                                                                                                                                                                post_id (str): ID del post de Facebook.

                                                                                                                                                                                                                                                                                                                                    Returns:
                                                                                                                                                                                                                                                                                                                                            List[Dict[str, Any]]: Lista de comentarios obtenidos del post.
                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                    url = f"https://graph.facebook.com/{post_id}/comments"
                                                                                                                                                                                                                                                                                                                                                        params = {
                                                                                                                                                                                                                                                                                                                                                                'access_token': access_token,
                                                                                                                                                                                                                                                                                                                                                                        'limit': 100
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                all_comments = []
                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                        while url:
                                                                                                                                                                                                                                                                                                                                                                                                data = fetch_from_facebook(url, params)
                                                                                                                                                                                                                                                                                                                                                                                                        comments = data.get('data', [])
                                                                                                                                                                                                                                                                                                                                                                                                                print(f"Fetched {len(comments)} comments for post {post_id}")
                                                                                                                                                                                                                                                                                                                                                                                                                        all_comments.extend(comments)
                                                                                                                                                                                                                                                                                                                                                                                                                                url = data.get('paging', {}).get('next')
                                                                                                                                                                                                                                                                                                                                                                                                                                        if url:
                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"Next page URL for comments: {url}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                        return all_comments

                                                                                                                                                                                                                                                                                                                                                                                                                                                        def fetch_reactions_for_post(access_token: str, post_id: str) -> List[Dict[str, Any]]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                Obtiene todas las reacciones de un post específico utilizando paginación.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Args:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                access_token (str): Token de acceso para la API de Facebook.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        post_id (str): ID del post de Facebook.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Returns:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    List[Dict[str, Any]]: Lista de reacciones obtenidas del post.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            url = f"https://graph.facebook.com/{post_id}/reactions"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                params = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'access_token': access_token,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'limit': 100
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        all_reactions = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                while url:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        data = fetch_from_facebook(url, params)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                reactions = data.get('data', [])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"Fetched {len(reactions)} reactions for post {post_id}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                all_reactions.extend(reactions)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        url = data.get('paging', {}).get('next')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if url:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"Next page URL for reactions: {url}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return all_reactions

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def fetch_group_data(access_token: str, group_id: str) -> List[Dict[str, Any]]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Obtiene todos los posts, comentarios y reacciones de un grupo de Facebook.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Args:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        access_token (str): Token de acceso para la API de Facebook.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                group_id (str): ID del grupo de Facebook.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Returns:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            List[Dict[str, Any]]: Lista de posts, cada uno con sus comentarios y reacciones.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"Starting data fetch for group: {group_id}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        posts = fetch_all_posts(access_token, group_id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for post in posts:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    post_id = post['id']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"Fetching comments and reactions for post {post_id}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    post['comments'] = fetch_comments_for_post(access_token, post_id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            post['reactions'] = fetch_reactions_for_post(access_token, post_id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"Completed data fetch for group: {group_id}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return posts

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ACCESS_TOKEN = 'YOUR_ACCESS_TOKEN'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            GROUP_ID = 'YOUR_GROUP_ID'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    group_data = fetch_group_data(ACCESS_TOKEN, GROUP_ID)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for post in group_data:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(post)
